use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'
pod 'AFNetworking'
pod 'SDWebImage'
pod 'Reachability'
pod 'MJRefresh'
pod 'MJExtension'
pod 'ReactiveCocoa'
pod 'ReactiveViewModel'
pod 'CMPopTipView'
pod 'FDFullscreenPopGesture'
pod 'IQKeyboardManager'
pod 'iOS-QR-Code-Encoder'
pod 'SDCycleScrollView'
pod 'EAIntroView'
pod 'MWPhotoBrowser'
pod 'JDStatusBarNotification'
pod 'PhotoTweaks'